### ISSUE TITLE
Typo a Consulta de les entitats adherides a una plataforma

### ISSUE THREAD

**Issue by ctrl-alt-d** [ConsorciAOC/eFact#4]
A la documentació de la [Consulta de les entitats adherides a una plataforma](https://github.com/ConsorciAOC/eFact/blob/master/ws-rcf/README.md#10-consulta-de-les-entitats-adherides-a-una-plataforma) trobem el següent text: 

>**ens:** Com que aquesta operació torna un màxim de 500 documents adjunts, en aquest camp s'indica si hi ha més adjunts, a part dels retornats, pendents de descàrrega per als paràmetres especificats. Possibles valors: true o false.

Aquí:

https://github.com/ConsorciAOC/eFact/blob/e31e4b72eacc289ecaadd429e784ad42065ff7aa/ws-rcf/README.md?plain=1#L593

Crec que hi ha hagut algun problema amb el copy-paste, perquè aquest text ens parla d'`ajunts` i estem consultant `ents`. I, a més, aquest camp, és una col·lecció i no pas un booleà.

**Comment by rgrange** [comment]
@ctrl-alt-d gracies per l'avís! Acabem de corregir l'errada a la documentació.
