### ISSUE TITLE
Resposta d'error diferent a la de la documentació

### ISSUE THREAD

**Issue by ghost** [ConsorciAOC/eFact#5]
Estic fent una petició a `https://efact-pre.aoc.cat/` amb un usuari incorrecte, la documentació indica que la resposta d'error tindrà el format:

```json
{
	"codiError": "9999",
	"descripcioError": "descripcio error" 
}
```

Tanmateix, jo estic revent:

```json
{
    "errorCode":1003,
    "errorInfo":"Usuari no vàlid"}
```

És a dir, amb les etiquetes amb anglès en comptes de català.

He posat l' [AcceptLanguage](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language) a `ca` a les capceleres i segueix apareixent amb anglès.

Em podeu indicar com haig de fer la petició pertal que, si hi ha un error, les etiquetes apareguin en català com a la documentació? (o bé si es tracta d'un error a la documentació)

D'altre banda, l'error code, arriba com un numèric i no com un string.

gràcies.

**Comment by JosepRamonC** [comment]
Significa això que tens claus d'accés assignades? @dani-herrera-udg

**Comment by rgrange** [comment]
Gracies per informar-nos d'aquest error.

En breu corregirem el missatge d'error que retorna el servei per tal que sigui:

```json
{
	"codiError": 9999,
	"descripcioError": "descripcio error" 
}
```

**Comment by rgrange** [comment]
Hem corregit el missatge d'error en tots els entorns.
